### ISSUE TITLE
Deliver pre-defined download image sizes/aspect ratios for UV/Lux

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#984]
Refer to Nik's wireframes for additional detail [Lux ticket 331](https://app.zenhub.com/workspaces/dlp-lux-5c75900b135e053ed882c4d0/issues/emory-libraries/dlp-lux/331)

The UV in Lux shows the following default image sizes available for download:

1. Current view 640 x 480 px (we assume this is supposed to be a screen capture of what the user is currently seeing in the Viewer)
2. Whole image 1000 x 750 px (seems to be hard-coded, and may distort some images)
3. Whole image 6488 x 3692 px (seems to be the full size of the image, varies per image)

Ticket items:

- [x] Investigate where these pre-defined sizes are generated (Cantaloupe?)
- [x] For Current View, investigate where this setting is controlled (it appears to be broken currently)
- [x] For the second size option shown above, if we can adjust this:
-- Investigate if we can provide percentage based sizes instead of fixed pixel based sizes, and provide an image that is 50% width and 50% height of its original 
--  OR, for the second size option shown above, if we cannot shift the dimension to a % based size, remove this second option 
- [x] Any pre-defined image sizes should be modified to preserve the original aspect ratio on any image sizes offered, so that the height or width is not distorted.

Examples of different aspect ratios for ingested images:

https://curate-test.library.emory.edu/concern/curate_generic_works/0580k6djhp-cor?locale=en
https://curate-test.library.emory.edu/concern/curate_generic_works/296wwpzgpb-cor?locale=en
https://curate-test.library.emory.edu/concern/curate_generic_works/68605qftvz-cor?locale=en

**Comment by devanshu-m** [comment]
* Current view and Whole Image Low Res options are currently not working as expected because of the hardcoded 640x480 width and height. This commit changes those fixed values to preservation master file's width and height. This should now fix the issue where the current view would sometimes show negative pixels and not download correctly. Along with this, distortion when downloading whole image low res (where height gets fixed at 750px) should also be fixed.

**Comment by eporter23** [comment]
@alexBLR @devanshu-m has this been deployed? I am still seeing the aspect ratio distortion and fixed medium size being applied. Here is an example: https://curate-test.library.emory.edu/iiif/2/96953700eb1dd2cd4a51a32d54f2bdeb923c2177/full/1000,750/0/default.jpg

**Comment by eporter23** [comment]
Also, do we need to deploy these changes to Lux as well?

**Comment by devanshu-m** [comment]
@eporter23 The manifest for the work you are testing this on will have to be regenerated for the change to take effect. Can you please send the work ID?
